# This is a basic workflow to help you get started with Actions

name: CI Build

on:
  push:
jobs:
  Build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        mode: [ Debug, ReleaseSafe, ReleaseSmall ]
        target: [ native, x86_64-linux-gnu, x86-linux-gnu, aarch64-linux-gnu, x86_64-macos, aarch64-macos, x86_64-windows, aarch64-windows ]
    name: ${{ matrix.os }}, ${{ matrix.target }}-${{ matrix.mode }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        name: Checkout repo

      - name: Install Zig
        uses: goto-bus-stop/setup-zig@v2
    
      - name: Build 
        run: zig build -Doptimize=${{ matrix.mode }} -Dtarget=${{ matrix.target }}

      - name: Upload
        if: matrix.os == 'ubuntu-latest' && matrix.target != 'native'
        uses: actions/upload-artifact@v3
        with:
          path: zig-out/bin
          name: ${{ matrix.target }} - ${{ matrix.mode }}
